name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: pip install -r ${{ github.workspace }}/requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m unittest

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: mypy ${{ github.workspace }}/

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: black --diff --check ${{ github.workspace }}/

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: isort --check-only ${{ github.workspace }}/

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: flake8 ${{ github.workspace }}/
