name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r module_30_ci_linters/requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m unittest

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: mypy module_30_ci_linters/

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: black --diff --check module_30_ci_linters/

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: isort --check-only module_30_ci_linters/

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: flake8 module_30_ci_linters/
