name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - run: python -m unittest ${{ github.workspace }}/tests.py

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - run: python -m mypy ${{ github.workspace }}/

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - run: python -m black -l 120 -S --diff --check ${{ github.workspace }}/

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - run: python -m isort --check-only ${{ github.workspace }}/

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - run: python -m flake8 --max-line-length 120 ${{ github.workspace }}/
