name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pip install -r ${{ github.workspace }}/requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m unittest ${{ github.workspace }}/tests

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m mypy ${{ github.workspace }}/

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m black --diff --check ${{ github.workspace }}/

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m isort --check-only ${{ github.workspace }}/

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m flake8 ${{ github.workspace }}/
