name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - run: python -m pip install -r ${{ github.workspace }}/requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: unitest
        uses: actions/checkout@v4
      - run: python -m unittest ${{ github.workspace }}/tests

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: mypy
        uses: actions/checkout@v4
      - run: python -m mypy ${{ github.workspace }}/

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: black
        uses: actions/checkout@v4
      - run: python -m black --diff --check ${{ github.workspace }}/

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: isort
        uses: actions/checkout@v4
      - run: python -m isort --check-only ${{ github.workspace }}/

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: flake8
        uses: actions/checkout@v4
      - run: python -m flake8 ${{ github.workspace }}/
