name: ci-linters
run-name: run linters
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: pip install -r ./requirements.txt

  unittest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: python -m unittest

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: mypy ./

  black:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: black --diff --check ./

  isort:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: isort --check-only ./

  flake8:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: flake8 ./
